# <"Let's try 3 min deep learning">

## importing modules

In [2]:
import tensorflow as tf
import numpy as np

## data_setup

In [6]:
# [hair, wings]
x_data=np.array([[0,0],[1,0],[1,1],[0,0],[0,0],[0,1]])
y_data=np.array([[1,0,0],[0,1,0],[0,0,1],[1,0,0],[1,0,0],[0,0,1]])

## placeholder setup

In [7]:
X=tf.placeholder(tf.float32) ## for input nodes
Y=tf.placeholder(tf.float32) ## for output nodes

## Variables setup

In [10]:
W=tf.Variable(tf.random_normal([2,3]))
b=tf.Variable(tf.zeros([3]))

## Layer Calculation

In [13]:
L=tf.add(tf.matmul(X,W),b)
L=tf.nn.relu(L)
model=tf.nn.softmax(L)
cost=tf.reduce_mean(-tf.reduce_sum(Y*tf.log(model),axis=1))

## Learning process

In [17]:
optimizer=tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op=optimizer.minimize(cost)

init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)

for step in range(100):
    sess.run(train_op,feed_dict={X:x_data,Y:y_data})
    
    if (step+1)%10 ==0:
        print(step+1,sess.run(cost,feed_dict={X:x_data,Y:y_data}))

10 0.8756632
20 0.8729903
30 0.87034774
40 0.86769724
50 0.8650551
60 0.8624962
70 0.8599736
80 0.8574615
90 0.85492426
100 0.8524773


In [19]:
prediction=tf.argmax(model,axis=1)
target=tf.argmax(Y,axis=1)
sess.run(prediction,feed_dict={X:x_data})
sess.run(target,feed_dict={Y:y_data})

array([0, 1, 2, 0, 0, 2], dtype=int64)

In [23]:
y_data

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1]])

In [24]:
sess.run(prediction,feed_dict={X:x_data})

array([0, 2, 2, 0, 0, 2], dtype=int64)

In [32]:
is_correct=tf.equal(prediction,target)
accuracy=tf.reduce_mean(tf.cast(is_correct,tf.float32))
print(sess.run(accuracy,feed_dict={X:x_data,Y:y_data}))

0.8333333
